package com.atlassian.plugin.connect.plugin.integration.plugins;

import com.atlassian.plugin.util.resource.AlternativeDirectoryResourceLoader;
import com.atlassian.sal.api.ApplicationProperties;
import com.atlassian.util.concurrent.CopyOnWriteMap;
import com.google.common.base.Joiner;
import com.google.common.base.Splitter;
import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.io.*;
import java.util.ArrayList;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.atomic.AtomicBoolean;

import static com.google.common.collect.Lists.newArrayList;

/**
 * This class loads a plugin called "atlassian-connect.i18n", which solely exists to store and expose generated i18n files
 * from remote descriptors.  Ideally, the products would support generated i18n resources, but currently they expect
 * them to be declared via <resource> tags pointing at physical files in the plugin.  This plugin is a way to get
 * around that.
 */
@Component
public class I18nPropertiesPluginManager implements InitializingBean
{
    private static final Logger log = LoggerFactory.getLogger(I18nPropertiesPluginManager.class);

    public static final String CACHES_DIR = "caches";
    public static final String I18N_FILE = "connect-addons.properties";
            
    private final AtomicBoolean started = new AtomicBoolean(false);
    private final Map<String, String> i18nToRegister = CopyOnWriteMap.newHashMap();
    private final ApplicationProperties applicationProperties;

    @Autowired
    public I18nPropertiesPluginManager(ApplicationProperties applicationProperties)
    {
        this.applicationProperties = applicationProperties;
    }

    /**
     * Register i18n properties for a newly installed plugin.
     */
    public synchronized void add(String addonKey, Properties i18nProperties) throws IOException
    {
        File i18nFile = ensureI18nFileExists();

        PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(i18nFile,true)));

        i18nProperties.store(out,"generated by the Atlassian Connect Plugin");
        
        //IOUtils.closeQuietly(out);
        
        out.close();
    }

    @Override
    public void afterPropertiesSet() throws Exception
    {
        killI18nFileIfNeeded();
        ensureI18nFileExists();
        updateSystemProperty();
    }

    private void killI18nFileIfNeeded()
    {
        File i18nFile = new File(getCacheDir(),I18N_FILE);
        
        if(i18nFile.exists())
        {
            FileUtils.deleteQuietly(i18nFile);
        }
    }

    private File ensureI18nFileExists() throws IOException
    {
        File cacheDir = getCacheDir();
        
        if(!cacheDir.exists())
        {
            FileUtils.forceMkdir(cacheDir);
        }
        
        File i18nFile = new File(cacheDir,I18N_FILE);
        
        if(!i18nFile.exists())
        {
            FileUtils.touch(i18nFile);
        }
        
        return i18nFile;
    }

    private void updateSystemProperty() throws IOException
    {
        ArrayList<String> dirs = newArrayList(Splitter.on(",").split(System.getProperty(AlternativeDirectoryResourceLoader.PLUGIN_RESOURCE_DIRECTORIES, "")));
        dirs.add(getCacheDir().getCanonicalPath());
        
        System.setProperty(AlternativeDirectoryResourceLoader.PLUGIN_RESOURCE_DIRECTORIES, Joiner.on(",").join(dirs));
    }
    
    private File getCacheDir()
    {
        return new File(applicationProperties.getHomeDirectory(),CACHES_DIR);
    }
}
