package com.atlassian.plugin.connect.jira.field.option;

import com.google.common.base.Preconditions;
import org.codehaus.jackson.JsonNode;

import java.util.Objects;

public final class ConnectFieldOption {
    private final Integer id;
    private final JsonNode value;
    private final ConnectFieldOptionScope scope;

    public static ConnectFieldOption of(Integer id, JsonNode value) {
        return new ConnectFieldOption(id, value, ConnectFieldOptionScope.GLOBAL);
    }

    public ConnectFieldOption withScope(ConnectFieldOptionScope scope) {
        return new ConnectFieldOption(id, value, scope);
    }

// The code below has been generated by Bob the Builder of Beans based on the class' fields.
// Everything after this comment will be regenerated if you invoke Bob again.
// If you don't know who Bob the Builder of Beans is, you can find him here: https://bitbucket.org/atlassian/bob

    private ConnectFieldOption(Integer id, JsonNode value, ConnectFieldOptionScope scope) {
        this.id = Preconditions.checkNotNull(id);
        this.value = Preconditions.checkNotNull(value);
        this.scope = Preconditions.checkNotNull(scope);
    }

    public Integer getId() {
        return id;
    }

    public JsonNode getValue() {
        return value;
    }

    public ConnectFieldOptionScope getScope() {
        return scope;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ConnectFieldOption that = (ConnectFieldOption) o;

        return Objects.equals(this.getId(), that.getId()) &&
                Objects.equals(this.getValue(), that.getValue()) &&
                Objects.equals(this.getScope(), that.getScope());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getValue(), getScope());
    }

    @Override
    public String toString() {
        return com.google.common.base.Objects.toStringHelper(this)
                .add("id", getId())
                .add("value", getValue())
                .add("scope", getScope())
                .toString();
    }
}
