package_includes:
  exclude:
    - "com.springframework*"
    - "org.apache.commons.logging*"
    - "com.atlassian.plugin.osgi.bridge.*"
    - "com.atlassian.sal.core*"
    - "com.atlassian.core*"
    - "org.apache.maven*"
    - "com.atlassian.plugin.remotable.host*"
    - "com.atlassian.plugin.remotable.container*"

  include:
    - "com.atlassian.*"
    - "com.google.common.*"
    - "javax.*"
    - "org.apache.*"
    - "org.bouncycastle*"
    - "org.dom4j*"
    - "org.jdom*"
    - "org.slf4j*"
    - "com.atlassian.activeobjects.spi*"
#    - "com.atlassian.plugin.remotable.api.service.jira"
    - "com.atlassian.jira.rest.client.domain"
    - "com.atlassian.event.api*"
    - "com.atlassian.plugin*"
    - "com.atlassian.sal*"
    - "com.atlassian.xmlrpc*"
    - "com.atlassian.security.random*"
    - "com.atlassian.fugue*"
    - "com.atlassian.mail*"
    - "com.google.common.*"
    - "com.google.inject*"
    - "org.objectweb.asm*"
    - "com.samskivert.*"
    - "javax.servlet*"
    - "javax.ws.rs*"
    - "net.oauth*"
    - "com.sun.mail.handlers"
    - "org.apache.commons.codec*"
    - "org.apache.log4j*"
    - "org.bouncycastle*"
    - "org.dom4j*"
    - "org.eclipse.jetty.*"
    - "org.jruby*"
    - "org.json"
    - "org.json.simple*"
    - "org.mozilla.javascript*"
    - "org.slf4j*"
    - "org.apache.log4j"
    - "org.yaml*"
    - "javax.inject"
    - "redstone.xmlrpc"
    - "org.joda.*"
    - "org.codehaus.jettison*"

package_versions:
  - {package: "com.atlassian.activeobjects.spi", version: "${ao.version}"}
  - {package: "com.atlassian.event.api*", version: "${event.version}"}
  - {package: "com.atlassian.plugin.remotable.api*", version: "${api.artifact.version}"}
  - {package: "com.atlassian.plugin.remotable.spi*", version: "${api.artifact.version}"}
  - {package: "com.atlassian.plugin", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.web*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.util*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.url*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.servlet*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.repositories*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.predicate*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.parsers*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.osgi*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.module*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.metadata*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.manager*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.main*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.loaders*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.impl*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.factories*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.event*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.elements*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.descriptors*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.classloader*", version: "${plugins.version}"}
  - {package: "com.atlassian.plugin.cache*", version: "${plugins.version}"}
  - {package: "com.atlassian.sal.api*", version: "${sal.version}"}
  - {package: "org.objectweb.asm*", version: "3.3.1"}
  - {package: "com.atlassian.security.random*", version: "${atlassian.security.version}"}

  # Even though Guava is newer, this is for backwards compatibility for those expecting collections
  - {package: "com.google.common.*", version: "1"}

  # This should be 3.0, but Spring will die as its package imports don't allow it
  - {package: "javax.servlet", version: "2.5"}
  - {package: "javax.servlet.http", version: "2.5"}

  - {package: "javax.inject", version: "1"}
  - {package: "org.apache.commons.codec*", version: "${commons.codec.version}"}
  - {package: "org.apache.commons.collections", version: "${commons.collections.version}"}
  - {package: "org.apache.commons.collections*", version: "${commons.collections.version}"}
  - {package: "org.apache.commons.lang*", version: "${commons.lang.version}"}
  - {package: "org.slf4j*", version: "${slf4j.version}"}
  - {package: "org.apache.log4j", version: "${log4j.version}"}
  - {package: "org.dom4j*", version: "${dom4j.version}"}
