package it.com.atlassian.plugin.connect.confluence.util;

import com.atlassian.confluence.content.service.PageService;
import com.atlassian.confluence.content.service.page.CreatePageCommand;
import com.atlassian.confluence.content.service.page.PageProvider;
import com.atlassian.confluence.content.service.page.SimpleContentPermissionProvider;
import com.atlassian.confluence.pages.Page;
import com.atlassian.confluence.spaces.Space;
import com.atlassian.confluence.spaces.SpaceManager;
import com.atlassian.user.EntityException;
import com.atlassian.user.User;
import com.atlassian.user.UserManager;

import static org.apache.commons.lang3.RandomStringUtils.randomAlphabetic;

public class ConfluenceTestUtil
{
    public static final String ADMIN_USERNAME = "admin";

    private final SpaceManager spaceManager;
    private final UserManager userManager;
    private final PageService pageService;

    public ConfluenceTestUtil(final SpaceManager spaceManager, final UserManager userManager, final PageService pageService)
    {
        this.spaceManager = spaceManager;
        this.userManager = userManager;
        this.pageService = pageService;
    }

    public Space createSpace()
    {
        String key = randomAlphabetic(6);
        return spaceManager.createSpace(key, "Space " + key, "Random space generated by ConfluenceTestUtil", getAdmin());
    }

    public Page createPage()
    {
        PageProvider pageProvider = () -> {
            Page page = new Page();
            page.setSpace(createSpace());
            return page;
        };

        SimpleContentPermissionProvider permissions = new SimpleContentPermissionProvider();

        CreatePageCommand serviceCommand = (CreatePageCommand) pageService.newCreatePageCommand(pageProvider, permissions, getAdmin(), false);
        serviceCommand.execute();
        return serviceCommand.getCreatedPage();
    }

    public User getAdmin()
    {
        try
        {
            return userManager.getUser(ADMIN_USERNAME);
        }
        catch (EntityException e)
        {
            throw new RuntimeException(e);
        }
    }
}
